### PR TITLE
Only check value of strings for faker

### PR DESCRIPTION
**Pull request by davetayls**
this fixes a bug where the task will fail if the value of a property is an integer

### CODE REVIEW

**Comment by chrisocast** [comment]
Hi @davetayls Im probably missing something obvious, but I'm having trouble reproducing the failing case this PR fixes. I ran a few tests and it looks like integers are handled fine via lines 43-45 in faker.js.

Can you give me an example of the bug in action? Thanks

**Comment by davetayls** [comment]
hey, sorry for taking so long to get back to you

It was choking on the following json

```
[{
    "id": 1,
    "text": "Text Content",
    "description": "{{Lorem.paragraphs(2)}}",
    "categories": [1,2,3,4]
}]
```

And I traced it to that line. Sorry should have included a test case along with the pull request. Does that JSON break it for you?

**Comment by davetayls** [comment]
shall i close this if you don't want to integrate it?

**Comment by dotnetCarpenter** [comment]
Using the current `grunt-faker@0.2.1` with your example gives me (without errors):

``` json
[
    {
        "categories": [1, 2, 3, 4],
        "description": "et dolor esse qui sit aut consequuntur quisquam id\ndicta fugit temporibus aut qui ut reprehenderit voluptatem\nomnis asperiores sit suscipit\n \r\tquia odit incidunt maxime omnis\nmolestiae aut ut\nquo quisquam eos\nveritatis itaque delectus ut nihil ea",
        "id": 1,
        "text": "Text Content"
    }
]
```

**Comment by davetayls** [comment]
@dotnetCarpenter ok great, that's the expected output :+1:

**Pull request closed without merging**
