### PR TITLE
Cumulative updates - new features bundle

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
I'm sorry but the other PR's quickly became a mess. I'm collecting all of them in this PR and making sure it passes travis-ci.

1) Update dependencies
2) Support writing output to multiple files, with different JSON data

``` javascript
faker: {
    slideDeck: {
        options: {
            jsonFormat: '<%= yeoman.app %>/data/slideDeck.faker.v1.js',
            out: ['<%= yeoman.app %>/data/slideDeck1.json', '<%= yeoman.app %>/data/slideDeck2.json']
        }
    }
}
```

3) When faking data you might want to do some pre/postfixing.
E.g: `"id": "sd{{Helpers.randomNumber(100)}}",` or `"id": "{{Helpers.randomNumber(1)}}0",` will output
`"id": "sd38",` or `"id": "50",`

### CODE REVIEW

**Comment by dotnetCarpenter** [comment]
@chrisocast What do you think?

**Comment by chrisocast** [comment]
@dotnetCarpenter Sorry about the delay. Will look into this tonight after work. Thanks!

**Comment by dotnetCarpenter** [comment]
No rush - albeit it would be nice if I didn't need to bind my current project to a fork but could mark this repo as a dependency.

**Comment by chrisocast** [comment]
This looks great. I tested the new features and everything is working as expected.

I added some unit tests today, which required making some similar updates to package.json, so there is a conflict showing up now unfortunately. If you can resolve that in your PR, I'll merge it.

**Comment by dotnetCarpenter** [comment]
Great! I'll look into it later today.

**Comment by dotnetCarpenter** [comment]
I've merged your changes and resolved the conflict in `package.json` but the tests are failing.

``` shell
npm test

> grunt-faker@0.2.0 test /Volumes/mystuff/dotnetCarpenter/Projects/buildTools/grunt-faker
> grunt

Running "clean:tests" (clean) task
Cleaning tmp...OK

Running "jshint:all" (jshint) task
>> 11 files lint free.

Running "clean:tests" (clean) task

Running "faker:test_all" (faker) task
>> The definitions module from Faker.js is not avail in this task.

Running "nodeunit:tests" (nodeunit) task
Testing address_test.js............OK
Testing company_test.jsF....
>> names - suffixes
>> Message: suffixes is a array
>> Error: 'string' === 'object'
>> at Object.exports.names.suffixes (test/company_test.js:15:10)
>> at Object.exports.names.setUp (test/company_test.js:8:5)

Testing faker_test.js.OK
Testing helpers_test.jsFF....FFF
>> names - randomNumber
>> Message: randomNumber is a number
>> Error: 'string' === 'number'
>> at Object.exports.names.randomNumber (test/helpers_test.js:15:10)
>> at Object.exports.names.setUp (test/helpers_test.js:8:5)

>> names - randomizeNum
>> Message: randomize is a number
>> Error: 'string' === 'number'
>> at Object.exports.names.randomizeNum (test/helpers_test.js:23:10)
>> at Object.exports.names.setUp (test/helpers_test.js:8:5)

>> names - shuffle
>> Message: shuffle created
>> Error: 9 === 5
>> at Object.exports.names.shuffle (test/helpers_test.js:62:10)
>> at Object.exports.names.setUp (test/helpers_test.js:8:5)

>> names - shuffle
>> Message: shuffle is an array
>> Error: 'string' === 'object'
>> at Object.exports.names.shuffle (test/helpers_test.js:63:10)
>> at Object.exports.names.setUp (test/helpers_test.js:8:5)

>> names - createCard
>> Error: Expected 9 assertions, 0 ran
>> at processImmediate [as _immediateCallback] (timers.js:330:15)

>> names - createCard
>> TypeError: Cannot read property 'length' of undefined
>> at Object.exports.names.createCard (test/helpers_test.js:70:27)
>> at Object.exports.names.setUp (test/helpers_test.js:8:5)

>> names - userCard
>> Error: Expected 8 assertions, 0 ran
>> at processImmediate [as _immediateCallback] (timers.js:330:15)

>> names - userCard
>> TypeError: Cannot read property 'length' of undefined
>> at Object.exports.names.userCard (test/helpers_test.js:85:27)
>> at Object.exports.names.setUp (test/helpers_test.js:8:5)

Testing internet_test.js.....OK
Testing lorem_test.jsF....
>> names - words
>> Message: words is an array
>> Error: 'string' === 'object'
>> at Object.exports.names.words (test/lorem_test.js:15:10)
>> at Object.exports.names.setUp (test/lorem_test.js:8:5)

Testing name_test.js...OK
Testing phone_number_test.js..OK
Testing random_test.jsFF.....................
>> random - number
>> Message: number is a number
>> Error: 'string' === 'number'
>> at Object.exports.random.number (test/random_test.js:15:10)
>> at Object.exports.random.setUp (test/random_test.js:8:5)

>> random - array_element
>> Message: array_element is a number
>> Error: 'string' === 'number'
>> at Object.exports.random.array_element (test/random_test.js:23:10)
>> at Object.exports.random.setUp (test/random_test.js:8:5)

Warning: 12/130 assertions failed (59ms) Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by dotnetCarpenter** [comment]
Hmm every number in `test_all.json` is written with quotation mark.

``` json
{"random.number(20)":"15"}
```

**Comment by dotnetCarpenter** [comment]
ok, fixed the number stuff in the latest commit. But are still seeing failing tests

**Comment by dotnetCarpenter** [comment]
@chrisocast Could you take another look? I've added some simple tests to test the pre-/post-fix options. `padding_test.js`

**Comment by chrisocast** [comment]
:thumbsup: thank you!

**Pull request merged**
